export interface DemoCar {
  id: string;
  seller_id: string;
  title: string;
  make_name: string;
  model_name: string;
  year: number;
  price: number;
  currency: string;
  country: string;
  city: string;
  location_display: string;
  mileage: number;
  mileage_unit: string;
  transmission: string;
  fuel_type: string;
  body_type: string;
  color: string;
  engine_size: string;
  condition: string;
  description: string;
  right_hand_drive: boolean;
  steering_side: string;
  available_for_export: boolean;
  shipping_info: string;
  import_duties_note: string;
  vin: string;
  featured: boolean;
  views: number;
  created_at: string;
  documents_verified: boolean;
  ntsa_verified: boolean;
  inspection_verified: boolean;
  pay_full: boolean;
  pay_deposit: boolean;
  pay_installments: boolean;
  deposit_percent: number;
  installment_months: number;
  installment_interest_rate: number;
  installment_monthly: number;
  yard_id: string;
  car_images: { image_url: string; is_primary: boolean; sort_order: number }[];
  car_yards: {
    id: string;
    slug: string;
    name: string;
    logo_url: string | null;
    city: string | null;
    country: string;
    is_approved: boolean;
  } | null;
  sellers: {
    id: string;
    business_name: string | null;
    country: string;
    city: string | null;
    location_display: string | null;
    is_verified: boolean;
    verification_badge: boolean;
    is_dealer: boolean;
    offers_local_pickup: boolean;
    offers_domestic_shipping: boolean;
    offers_international_shipping: boolean;
  } | null;
}

export interface DemoYard {
  id: string;
  slug: string;
  name: string;
  tagline: string | null;
  description: string | null;
  logo_url: string | null;
  cover_url: string | null;
  country: string;
  city: string | null;
  address: string | null;
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  opening_hours: string | null;
  is_featured: boolean;
  sellers: { verification_badge: boolean; is_verified: boolean } | null;
}

export const DEMO_YARDS: DemoYard[] = [
  {
    id: "yard-1",
    slug: "nairobi-hub",
    name: "AutoConnect Nairobi Central Yard",
    tagline: "Premier Verified Logistics Hub & Inspection Center",
    description: "Located on Ngong Road, Nairobi. Fully equipped with multi-point automated vehicle diagnostic bays, secure escrow storage, physical vehicle viewing, and automated biometric gate pass issuance.",
    logo_url: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=400&auto=format&fit=crop&q=80",
    cover_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&auto=format&fit=crop&q=80",
    country: "KE",
    city: "Nairobi",
    address: "Ngong Road, Junction Bay 14, Nairobi",
    phone: "+254 700 889 900",
    whatsapp: "+254 700 889 900",
    email: "nairobi.yard@autoconnect.dev",
    opening_hours: "Mon - Sat: 8:00 AM - 6:30 PM",
    is_featured: true,
    sellers: { verification_badge: true, is_verified: true },
  },
  {
    id: "yard-2",
    slug: "mombasa-port-hub",
    name: "Mombasa Port Logistics & Customs Yard",
    tagline: "KPA Port Customs Clearance & Clearing Bay",
    description: "Direct access to Kilindini Harbour, Port of Mombasa. Specialized in KRA customs duty clearance, KEBS verification, and secure container de-stuffing.",
    logo_url: "https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=400&auto=format&fit=crop&q=80",
    cover_url: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=1200&auto=format&fit=crop&q=80",
    country: "KE",
    city: "Mombasa",
    address: "Mbaraki Port Access Rd, Mombasa Port",
    phone: "+254 711 334 455",
    whatsapp: "+254 711 334 455",
    email: "mombasa.logistics@autoconnect.dev",
    opening_hours: "24/7 Port Logistics Operations",
    is_featured: true,
    sellers: { verification_badge: true, is_verified: true },
  },
  {
    id: "yard-3",
    slug: "yokohama-export-terminal",
    name: "Yokohama Direct Export Terminal",
    tagline: "JEVIC & QISJ Certified Export Bay Japan",
    description: "Honmoku Pier, Yokohama Port. Full pre-shipment radiation inspection, genuine odometer verification, and RoRo/Container shipping directly to East Africa.",
    logo_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&auto=format&fit=crop&q=80",
    cover_url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&auto=format&fit=crop&q=80",
    country: "JP",
    city: "Yokohama",
    address: "Honmoku Pier 7, Naka Ward, Yokohama, Kanagawa",
    phone: "+81 45 228 9011",
    whatsapp: "+81 90 1234 5678",
    email: "export@yokohamaexport.jp",
    opening_hours: "Mon - Fri: 9:00 AM - 6:00 PM JST",
    is_featured: true,
    sellers: { verification_badge: true, is_verified: true },
  },
];

export const DEMO_CARS: DemoCar[] = [
  {
    id: "car-1",
    seller_id: "demo-seller-kenji",
    title: "2021 Toyota Land Cruiser Prado TX-L 2.8D",
    make_name: "Toyota",
    model_name: "Land Cruiser Prado",
    year: 2021,
    price: 6850000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya (In Yard)",
    mileage: 42300,
    mileage_unit: "km",
    transmission: "Automatic",
    fuel_type: "Diesel",
    body_type: "SUV",
    color: "Pearl White",
    engine_size: "2800cc (1GD-FTV)",
    condition: "Foreign Used - Grade 4.5A",
    description: "Mint condition 2021 Land Cruiser Prado TX-L package. 7-seater leather interior, sunroof, 360-degree cameras, radar cruise control, KDSS suspension, genuine verified mileage, clean title ready for instant handover via escrow.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "Available for immediate pickup in Nairobi Yard or express domestic flatbed dispatch within 24 hours.",
    import_duties_note: "Fully duty paid. Tax clearance certificate and roadworthiness inspection certificate included.",
    vin: "JTEBX3FJ8M0291844",
    featured: true,
    views: 1842,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 256000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
      {
        image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 1,
      },
      {
        image_url: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 2,
      },
      {
        image_url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 3,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=400&auto=format&fit=crop&q=80",
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-2",
    seller_id: "demo-seller-kenji",
    title: "2021 Toyota Harrier Hybrid G-Edition",
    make_name: "Toyota",
    model_name: "Harrier",
    year: 2021,
    price: 4450000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 48000,
    mileage_unit: "km",
    transmission: "E-CVT Automatic",
    fuel_type: "Petrol Hybrid",
    body_type: "SUV",
    color: "Pearl Crystal White",
    engine_size: "2500cc Hybrid (A25A-FXS)",
    condition: "Foreign Used - Grade 4.5A",
    description: "Exceptional 2021 Toyota Harrier Hybrid G-Edition. 22 km/L fuel efficiency, leather trimmed seats, digital inner mirror with front & rear drive recorder, power back door, Toyota Safety Sense 2.0.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "Located in Nairobi yard. Inspected with 150-point checklist.",
    import_duties_note: "All customs and import taxes fully cleared.",
    vin: "AXUH80-0042918",
    featured: true,
    views: 1250,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 25,
    installment_months: 18,
    installment_interest_rate: 12.0,
    installment_monthly: 162000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
      {
        image_url: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 1,
      },
      {
        image_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 2,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-3",
    seller_id: "demo-seller-kenji",
    title: "2020 Mercedes-Benz C200 AMG Line",
    make_name: "Mercedes-Benz",
    model_name: "C-Class",
    year: 2020,
    price: 4800000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 41000,
    mileage_unit: "km",
    transmission: "Automatic (9G-TRONIC)",
    fuel_type: "Petrol Hybrid (EQ Boost)",
    body_type: "Sedan",
    color: "Iridium Silver Metallic",
    engine_size: "1500cc Turbo + 48V Mild Hybrid",
    condition: "Foreign Used - Grade 4.5B",
    description: "Immaculate Mercedes-Benz C200 AMG Line facelift. Full digital cockpit, panoramic glass roof, ambient lighting, AMG flat-bottom steering wheel, Burmester sound, full dealer service record.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "In yard, ready for viewing and test drive.",
    import_duties_note: "Duty fully verified. Zero encumbrance.",
    vin: "WDD2050772R189421",
    featured: true,
    views: 980,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 165000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
      {
        image_url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 1,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-4",
    seller_id: "demo-seller-kenji",
    title: "2021 BMW 530i M Sport",
    make_name: "BMW",
    model_name: "5 Series",
    year: 2021,
    price: 5400000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 38000,
    mileage_unit: "km",
    transmission: "8-Speed Steptronic",
    fuel_type: "Petrol",
    body_type: "Sedan",
    color: "Phytonic Blue Metallic",
    engine_size: "2000cc TwinPower Turbo (248 HP)",
    condition: "Foreign Used - Grade 4.5A",
    description: "Flagship executive BMW 530i M Sport package. Dakota Cognac leather interior, Live Cockpit Professional with 12.3-inch display, head-up display, adaptive M suspension, Harman Kardon audio system.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "In yard, ready for inspection and handover.",
    import_duties_note: "Duty fully cleared.",
    vin: "WBAJA7200M0829141",
    featured: true,
    views: 1120,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 198000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-5",
    seller_id: "demo-seller-kenji",
    title: "2021 Toyota Hilux Double Cab 2.8 GD-6 4x4",
    make_name: "Toyota",
    model_name: "Hilux",
    year: 2021,
    price: 4600000,
    currency: "KES",
    country: "KE",
    city: "Nakuru",
    location_display: "Nakuru, Kenya",
    mileage: 52000,
    mileage_unit: "km",
    transmission: "6-Speed Automatic 4WD",
    fuel_type: "Diesel",
    body_type: "Pickup",
    color: "Attitude Black Mica",
    engine_size: "2800cc Turbo Diesel (500 Nm)",
    condition: "Local Used - Grade 4.5",
    description: "Legendary off-road durability. 2.8L GD-6 diesel powertrain with rear differential lock, Downhill Assist Control, Apple CarPlay / Android Auto touchscreen, heavy-duty bed liner, tow bar, and bull bar.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "Located in Nakuru, available for viewing or transfer to Nairobi hub.",
    import_duties_note: "Clean private logbook, immediate escrow transfer.",
    vin: "AHTBA3CD907812903",
    featured: true,
    views: 1450,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 172000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-6",
    seller_id: "demo-seller-kenji",
    title: "2022 Ford Ranger Wildtrak 2.0 Bi-Turbo 4x4",
    make_name: "Ford",
    model_name: "Ranger",
    year: 2022,
    price: 4950000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 36000,
    mileage_unit: "km",
    transmission: "10-Speed Automatic 4WD",
    fuel_type: "Diesel",
    body_type: "Pickup",
    color: "Pride Orange Metallic",
    engine_size: "2000cc Bi-Turbo Diesel (210 HP)",
    condition: "Foreign Used - Grade 5A",
    description: "Premium overland pickup truck. Terrain Management System, powered roller shutter bed, heated leather Wildtrak seats, adaptive cruise control, 3.5-ton towing capability with integrated trailer brake controller.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "In yard, ready for inspection.",
    import_duties_note: "Duty fully cleared.",
    vin: "MNBUMFF50NW719823",
    featured: true,
    views: 1040,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 184000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-7",
    seller_id: "demo-seller-kenji",
    title: "2020 Mercedes-Benz E300 AMG Line",
    make_name: "Mercedes-Benz",
    model_name: "E-Class",
    year: 2020,
    price: 5800000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 41000,
    mileage_unit: "km",
    transmission: "Automatic (9G-TRONIC)",
    fuel_type: "Petrol",
    body_type: "Sedan",
    color: "Obsidian Black Metallic",
    engine_size: "2000cc Turbo (255 HP)",
    condition: "Foreign Used - Grade 4.5A",
    description: "Executive luxury saloon with panoramic glass sunroof, Burmester 13-speaker 590W surround sound system, widescreen dual 12.3-inch cockpit, 64-color ambient lighting, and AMG Line styling package.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "In Nairobi yard, ready for viewing.",
    import_duties_note: "Duty fully cleared.",
    vin: "WDD2130832A918234",
    featured: true,
    views: 860,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 215000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-8",
    seller_id: "demo-seller-kenji",
    yard_id: "yard-1",
    title: "2020 Subaru Outback 2.5i Limited EyeSight",
    make_name: "Subaru",
    model_name: "Outback",
    year: 2020,
    price: 3650000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 49800,
    mileage_unit: "km",
    transmission: "Lineartronic CVT",
    fuel_type: "Petrol",
    body_type: "Wagon / Crossover",
    color: "Tungsten Metallic",
    engine_size: "2500cc Boxer",
    condition: "Foreign Used - Grade 4.5A",
    description: "Rugged elegance with Subaru Symmetrical All-Wheel Drive and X-MODE with Hill Descent Control. EyeSight driver assist technology, Harman Kardon sound, dual-zone climate, heated leather seats.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "In yard, ready for inspection.",
    import_duties_note: "Duty fully cleared.",
    vin: "JF2BS9CL4G0192841",
    featured: true,
    views: 890,
    created_at: new Date(Date.now() - 86400000 * 9).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 20,
    installment_months: 24,
    installment_interest_rate: 11.5,
    installment_monthly: 138000,
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
      {
        image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 1,
      },
      {
        image_url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 2,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
  {
    id: "car-9",
    seller_id: "demo-seller-kenji",
    title: "2020 Mazda CX-5 2.2D AWD Exclusive-Mode",
    make_name: "Mazda",
    model_name: "CX-5",
    year: 2020,
    price: 3450000,
    currency: "KES",
    country: "KE",
    city: "Nairobi",
    location_display: "Nairobi, Kenya",
    mileage: 38200,
    mileage_unit: "km",
    transmission: "Automatic",
    fuel_type: "Diesel",
    body_type: "SUV",
    color: "Soul Red Crystal",
    engine_size: "2200cc SkyActiv-D",
    condition: "Foreign Used - Grade 5A",
    description: "Top-tier Mazda CX-5 Exclusive Mode. Nappa leather seats with front ventilation, Bose 10-speaker premium audio, Head-Up Display (HUD), lane keep assist, smart brake support, power tailgate.",
    right_hand_drive: true,
    steering_side: "right",
    available_for_export: true,
    shipping_info: "Located in Nairobi yard. Inspected with 150-point checklist.",
    import_duties_note: "All customs and import taxes cleared.",
    vin: "JM3KF4WLA00318921",
    featured: true,
    views: 1250,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    documents_verified: true,
    ntsa_verified: true,
    inspection_verified: true,
    pay_full: true,
    pay_deposit: true,
    pay_installments: true,
    deposit_percent: 25,
    installment_months: 18,
    installment_interest_rate: 12.0,
    installment_monthly: 162000,
    yard_id: "yard-1",
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
        sort_order: 0,
      },
      {
        image_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 1,
      },
      {
        image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80",
        is_primary: false,
        sort_order: 2,
      },
    ],
    car_yards: {
      id: "yard-1",
      slug: "nairobi-hub",
      name: "AutoConnect Nairobi Central Yard",
      logo_url: null,
      city: "Nairobi",
      country: "KE",
      is_approved: true,
    },
    sellers: {
      id: "demo-seller-kenji",
      business_name: "Kenji Auto Export & Direct Motors",
      country: "KE",
      city: "Nairobi",
      location_display: "Nairobi, Kenya",
      is_verified: true,
      verification_badge: true,
      is_dealer: true,
      offers_local_pickup: true,
      offers_domestic_shipping: true,
      offers_international_shipping: true,
    },
  },
];

export const DEMO_TRANSACTION = {
  id: "tx-1",
  status: "payment_received",
  display_currency: "KES",
  display_car_price: 6850000,
  display_service_fee: 102750,
  display_total: 6952750,
  initiated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  paid_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  released_at: null,
  disputed_at: null,
  buyer_id: "demo-buyer-alice",
  car_id: "car-1",
  payment_method: "mpesa",
  manual_channel: "mpesa",
  manual_reference: "QK879XJ391",
  handover_ready_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  cars: {
    title: "2021 Toyota Land Cruiser Prado TX-L 2.8D",
    year: 2021,
    car_images: [
      {
        image_url: "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?w=1200&auto=format&fit=crop&q=80",
        is_primary: true,
      },
    ],
  },
  sellers: {
    business_name: "Kenji Auto Export & Direct Motors",
    country: "KE",
  },
};
