import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { BadgeCheck, CalendarPlus, CarFront, MapPin, ShieldCheck, Wrench } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/EmptyState";
import { Skeleton } from "@/components/ui/skeleton";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [{ title: "Mechanics & Garages — AutoConnect" }] }), component: ServicesPage });
type Provider = { id: string; name: string; provider_type: string; country: string; city: string | null; description: string | null; phone: string | null; is_verified: boolean };
const labels: Record<string, string> = { mechanic: "Mechanic", garage: "Garage", inspection: "Inspection", logistics: "Logistics", insurance: "Insurance", roadside: "Roadside help" };

function ServicesPage() {
  const providers = useQuery({ queryKey: ["approved-service-providers"], queryFn: async () => { const response = await fetch("/api/public/service-providers"); const payload = await response.json() as { data?: Provider[]; error?: string }; if (!response.ok) throw new Error(payload.error ?? "Unable to load providers."); return payload.data ?? []; } });
  return <main className="mx-auto max-w-[1180px] px-4 py-8 sm:px-6 lg:py-12"><section className="rounded-3xl border bg-slate-950 p-7 text-white shadow-xl sm:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-300">Car care network</p><h1 className="mt-3 max-w-2xl text-3xl font-extrabold tracking-tight sm:text-4xl">A trusted next step after you buy.</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-300 sm:text-base">Find mechanics, garages and inspection providers in one calm directory. You keep control of every contact and appointment.</p><div className="mt-6 flex flex-wrap gap-3"><Button asChild className="bg-teal-400 text-slate-950 hover:bg-teal-300"><Link to="/garage">Open My Garage</Link></Button><Button asChild variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white"><Link to="/parts">Find parts</Link></Button></div></section>{providers.isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3].map((i) => <Skeleton className="h-60 rounded-2xl" key={i} />)}</div> : providers.isError ? <EmptyState icon={<Wrench />} title="Service directory is unavailable" description="Please refresh and try again." /> : providers.data?.length ? <section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{providers.data.map((provider) => <ProviderCard key={provider.id} provider={provider} />)}</section> : <EmptyState icon={<Wrench />} title="No service providers yet" description="Approved mechanics and garages will appear here." />}</main>;
}
function ProviderCard({ provider }: { provider: Provider }) { return <article className="flex min-h-60 flex-col rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><Wrench className="h-5 w-5" /></span><span className="rounded-full bg-muted px-2.5 py-1 text-[11px] font-bold">{labels[provider.provider_type] ?? provider.provider_type}</span></div><h2 className="mt-5 text-lg font-bold">{provider.name}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{provider.description ?? "Approved AutoConnect service provider."}</p><p className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5 text-primary" />{provider.city ? `${provider.city}, ` : ""}{provider.country}</p>{provider.is_verified && <p className="mt-2 flex items-center gap-1 text-xs font-semibold text-teal-700"><BadgeCheck className="h-3.5 w-3.5" /> Verified provider</p>}<Button onClick={() => toast.info("Preview appointment request — sign in to contact a provider.")} className="mt-auto w-full" size="sm"><CalendarPlus className="mr-2 h-4 w-4" /> Request appointment</Button></article>; }
