import { useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, ClipboardCheck, Gavel, Pause, Play, RotateCcw, Search, ShieldCheck, Sparkles, Volume2, VolumeX, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";

type DemoScene = { time: string; kicker: string; title: string; body: string; action: string; to: string; icon: typeof Search; kind: "search" | "vehicle" | "auction" | "garage" | "seller" | "admin" };

const scenes: DemoScene[] = [
  { time: "00:00", kicker: "THE FULL JOURNEY", title: "Everything around your car, finally connected.", body: "A calmer way to find, decide, buy, own and sell—with the important facts kept together.", action: "Start exploring", to: "/cars", icon: Sparkles, kind: "search" },
  { time: "00:07", kicker: "FIND WITH CONTEXT", title: "Search by what you need, not just a make and model.", body: "Filter cars, compare supplied evidence, and contact a seller with your questions already organised.", action: "Browse cars", to: "/cars", icon: Search, kind: "search" },
  { time: "00:14", kicker: "DECIDE WITH EVIDENCE", title: "A vehicle page built for a real decision.", body: "Condition notes, documents, viewing requests and next steps stay in one uncluttered view.", action: "See vehicle checks", to: "/trust", icon: ShieldCheck, kind: "vehicle" },
  { time: "00:21", kicker: "MOVE FAST, SAFELY", title: "Live auctions without the mystery.", body: "See the time, price, evidence and masked bid trail. A winner moves to a reservation, not a fake payment confirmation.", action: "View auctions", to: "/auctions", icon: Gavel, kind: "auction" },
  { time: "00:28", kicker: "OWN WITH MEMORY", title: "Your car becomes a living record.", body: "Services, fitted parts, mileage, receipts and reminders remain attached to the vehicle you actually own.", action: "Open My Garage", to: "/garage", icon: Wrench, kind: "garage" },
  { time: "00:35", kicker: "SELL AND OPERATE", title: "Trust is a workflow, not a badge.", body: "Sellers submit evidence and manage enquiries. Your team records listing, auction and dispute decisions in one control room.", action: "See seller tools", to: "/seller", icon: ClipboardCheck, kind: "admin" },
];

export function ProductDemoReel({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  const [index, setIndex] = useState(0);
  const [playing, setPlaying] = useState(true);
  const [muted, setMuted] = useState(true);
  const video = useRef<HTMLVideoElement>(null);
  const scene = scenes[index];
  useEffect(() => { if (!open || !playing) return; const timer = window.setInterval(() => setIndex((value) => (value + 1) % scenes.length), 7000); return () => window.clearInterval(timer); }, [open, playing]);
  useEffect(() => { if (!open) { setIndex(0); setPlaying(true); return; } void video.current?.play().catch(() => setPlaying(false)); }, [open]);
  useEffect(() => { if (!video.current) return; video.current.muted = muted; if (playing) void video.current.play().catch(() => setPlaying(false)); else video.current.pause(); }, [muted, playing]);
  const choose = (value: number) => { setIndex(value); setPlaying(true); if (video.current) video.current.currentTime = value * 4; };
  const replay = () => { choose(0); if (video.current) video.current.currentTime = 0; };

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[96vh] max-w-7xl overflow-y-auto rounded-[30px] border border-slate-200 bg-white p-0 text-slate-950 shadow-2xl sm:max-h-[92vh]"><div className="overflow-hidden">
    <header className="relative isolate min-h-[275px] overflow-hidden bg-slate-950 p-6 text-white sm:p-9"><video ref={video} autoPlay muted={muted} loop playsInline preload="metadata" poster="/images/hero-driving-suv.jpg" className="absolute inset-0 h-full w-full object-cover opacity-55"><source src="/videos/hero-driving-car.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(2,6,23,.92),rgba(2,6,23,.58),rgba(2,6,23,.22))]"/><div className="relative flex min-h-[225px] flex-col justify-between"><div className="flex items-center justify-between gap-4"><span className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-3 py-1.5 text-[10px] font-extrabold tracking-[.18em] backdrop-blur"><span className="h-2 w-2 animate-pulse rounded-full bg-teal-300"/>AUTOCONNECT PRODUCT FILM</span><span className="font-mono text-xs text-slate-300">{scene.time} / 00:42</span></div><div className="max-w-2xl"><p className="text-[11px] font-bold tracking-[.18em] text-teal-200">{scene.kicker}</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-5xl">{scene.title}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-slate-200 sm:text-base">{scene.body}</p></div></div></header>
    <div className="grid lg:grid-cols-[1.05fr_.95fr]"><div className="border-b border-slate-200 bg-[#f8fafc] p-5 sm:p-8 lg:border-b-0 lg:border-r"><DemoScreen scene={scene}/></div><div className="flex flex-col justify-between p-5 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-700">The story</p><h3 className="mt-2 text-2xl font-extrabold tracking-tight">A guided tour of the whole platform.</h3><p className="mt-3 text-sm leading-6 text-slate-600">This product film follows the real areas of AutoConnect. Choose any chapter, then open the actual feature when you are ready.</p><div className="mt-6 space-y-2">{scenes.map((item, itemIndex) => <button type="button" key={item.title} onClick={() => choose(itemIndex)} className={`flex w-full items-center gap-3 rounded-2xl p-3 text-left transition ${itemIndex === index ? "bg-teal-50 ring-1 ring-teal-200" : "hover:bg-slate-50"}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-xl text-xs font-extrabold ${itemIndex === index ? "bg-teal-500 text-slate-950" : "bg-slate-100 text-slate-500"}`}>{String(itemIndex + 1).padStart(2, "0")}</span><span className="min-w-0"><span className="block text-sm font-bold text-slate-900">{item.kicker}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{item.title}</span></span></button>)}</div></div><div className="mt-7 flex flex-wrap gap-3"><Button asChild className="rounded-xl bg-slate-950 text-white hover:bg-slate-800"><Link to={scene.to as never} onClick={() => onOpenChange(false)}>{scene.action}<ArrowRight className="ml-2 h-4 w-4"/></Link></Button><Button type="button" variant="outline" className="rounded-xl" onClick={replay}><RotateCcw className="mr-2 h-4 w-4"/>Replay</Button></div></div></div>
    <footer className="flex flex-wrap items-center gap-x-5 gap-y-3 border-t border-slate-200 bg-white px-5 py-4 sm:px-8"><button type="button" onClick={() => setPlaying((value) => !value)} className="inline-flex items-center gap-2 text-sm font-bold text-slate-800">{playing ? <Pause className="h-4 w-4 text-teal-600"/> : <Play className="h-4 w-4 text-teal-600"/>}{playing ? "Pause film" : "Play film"}</button><button type="button" onClick={() => setMuted((value) => !value)} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600">{muted ? <VolumeX className="h-4 w-4"/> : <Volume2 className="h-4 w-4"/>}{muted ? "Sound off" : "Sound on"}</button><span className="ml-auto text-xs text-slate-500">Tap a chapter to jump ahead</span></footer>
  </div></DialogContent></Dialog>;
}

function DemoScreen({ scene }: { scene: DemoScene }) {
  const Icon = scene.icon;
  return <div className="overflow-hidden rounded-[26px] border border-slate-200 bg-white p-3 shadow-[0_22px_60px_rgba(15,23,42,.12)] sm:p-4"><div className="flex items-center justify-between rounded-2xl border border-slate-200 px-4 py-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-slate-950 text-teal-300"><Sparkles className="h-4 w-4"/></span><div><p className="text-sm font-extrabold">Auto<span className="text-teal-600">Connect</span></p><p className="text-[9px] font-bold tracking-[.16em] text-slate-400">LIVE PRODUCT TOUR</p></div></div><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-400"/></div><div className="mt-3 min-h-[330px] rounded-2xl border border-slate-200 p-5 sm:min-h-[410px] sm:p-7"><div className="mb-6 flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[.16em] text-teal-700">{scene.kicker}</p><h3 className="mt-1 text-xl font-extrabold">{scene.kind === "search" ? "Find your right fit" : scene.kind === "vehicle" ? "Vehicle evidence" : scene.kind === "auction" ? "Live offer desk" : scene.kind === "garage" ? "Family Tank" : scene.kind === "admin" ? "Marketplace control tower" : "Seller workspace"}</h3></div><span className="grid h-10 w-10 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Icon className="h-5 w-5"/></span></div><ScreenBody kind={scene.kind}/></div><div className="mt-3 flex items-center gap-2 rounded-xl bg-teal-50 px-3 py-2 text-[11px] font-medium text-teal-800"><ShieldCheck className="h-3.5 w-3.5"/>A real route, a clear next step, and an honest status.</div></div>;
}

function ScreenBody({ kind }: { kind: DemoScene["kind"] }) {
  if (kind === "search") return <><div className="rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-300">I need a reliable family SUV</p><div className="mt-3 flex items-center gap-2 rounded-xl bg-white/10 p-2.5"><Search className="h-4 w-4 text-teal-300"/><span className="text-sm font-semibold">Toyota Harrier under KSh 4M</span></div></div><div className="mt-4 grid grid-cols-[.9fr_1.1fr] gap-3"><div className="h-28 rounded-xl bg-[linear-gradient(140deg,#d8f3f0,#86cfc8)]"/><div><p className="font-bold">2021 Toyota Harrier</p><p className="mt-1 text-xs text-slate-500">KSh 3,850,000 · Nairobi</p><div className="mt-3 flex gap-1.5"><Tag text="Evidence"/><Tag text="Compare"/><Tag text="Viewing"/></div></div></div></>;
  if (kind === "vehicle") return <><div className="grid grid-cols-2 gap-3"><Metric value="4 / 4" label="Evidence items"/><Metric value="KES 3.85M" label="Vehicle price"/></div><div className="mt-4 space-y-2"><Row title="Seller identity" detail="Submitted for review" tone="teal"/><Row title="Inspection evidence" detail="Shown only when verified" tone="slate"/><Row title="Arrange viewing" detail="Choose a time before deciding" tone="amber"/></div></>;
  if (kind === "auction") return <><div className="rounded-2xl bg-slate-950 p-4 text-white"><div className="flex justify-between text-xs text-teal-200"><span>LIVE AUCTION</span><span>ENDS IN 01:14:22</span></div><p className="mt-3 text-xl font-extrabold">Toyota Prado TX</p><p className="mt-2 text-2xl font-extrabold text-teal-300">KSh 4,800,000</p></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric value="KSh 50K" label="Next minimum"/><Metric value="07" label="Masked bids"/></div><p className="mt-4 rounded-xl border border-teal-100 bg-teal-50 p-3 text-xs leading-5 text-teal-900">Winner proceeds to a timed reservation. Payment cannot be shown as complete without verified evidence.</p></>;
  if (kind === "garage") return <><div className="grid grid-cols-3 gap-2"><Metric value="68,240" label="Mileage"/><Metric value="3" label="Reminders"/><Metric value="12" label="Records"/></div><div className="mt-4 space-y-2"><Row title="Routine service" detail="Completed · Receipt added" tone="teal"/><Row title="Brake pads" detail="Parts quote requested" tone="slate"/><Row title="Inspection" detail="Due in 14 days" tone="amber"/></div></>;
  return <><div className="grid grid-cols-2 gap-3"><Metric value="12" label="Evidence review"/><Metric value="03" label="Auction approval"/><Metric value="02" label="Disputes"/><Metric value="07" label="Provider claims"/></div><div className="mt-4 rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs font-bold tracking-[.14em] text-teal-300">RECORDED DECISION</p><p className="mt-2 font-bold">Vehicle evidence ready for review</p><div className="mt-3 flex items-center justify-between text-xs text-slate-300"><span>Seller submitted today</span><span className="rounded-lg bg-teal-400 px-2 py-1 font-bold text-slate-950">Review</span></div></div></>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="text-lg font-extrabold">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</p></div>; }
function Tag({ text }: { text: string }) { return <span className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-[10px] font-semibold text-slate-600">{text}</span>; }
function Row({ title, detail, tone }: { title: string; detail: string; tone: string }) { return <div className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div><p className="text-sm font-bold">{title}</p><p className="mt-0.5 text-[11px] text-slate-500">{detail}</p></div><span className={`h-2.5 w-2.5 rounded-full ${tone === "teal" ? "bg-teal-500" : tone === "amber" ? "bg-amber-400" : "bg-slate-400"}`}/></div>; }
