import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, FileCheck2, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/layout/PageHeader";

export const Route = createFileRoute("/_authenticated/admin/evidence")({ component: AdminEvidence });
function AdminEvidence() { const qc = useQueryClient(); const { data, isLoading, isError } = useQuery({ queryKey:["admin-vehicle-evidence"], queryFn:async()=>{ const { data,error }=await supabase.from("vehicle_evidence").select("id,title,evidence_type,source_url,status,is_public,created_at,cars(title)").order("created_at",{ascending:false}); if(error) throw error; return (data??[]) as any[]; }}); const review=async(row:any,status:"verified"|"rejected")=>{ const {data:{user}}=await supabase.auth.getUser(); const {error}=await supabase.from("vehicle_evidence").update({status,is_public:status==="verified",reviewed_by:user?.id,reviewed_at:new Date().toISOString()}).eq("id",row.id); if(error)return toast.error(error.message); toast.success(status==="verified"?"Evidence verified and published":"Evidence rejected"); qc.invalidateQueries({queryKey:["admin-vehicle-evidence"]}); }; return <div className="space-y-6"><PageHeader eyebrow="Trust operations" title="Vehicle evidence review" description="Only source documents you have reviewed can be marked verified or shown publicly."/>{isLoading?<p className="text-sm text-muted-foreground">Loading evidence…</p>:isError?<div className="rounded-2xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive">Evidence queue could not load. This is not an empty result.</div>:<div className="overflow-hidden rounded-2xl border bg-card">{data?.length?data.map((row)=><div className="flex flex-wrap items-center justify-between gap-4 border-b p-5 last:border-0" key={row.id}><div><p className="font-semibold">{row.title}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{(Array.isArray(row.cars)?row.cars[0]:row.cars)?.title||"Vehicle"} · {row.evidence_type.replaceAll("_"," ")} · {row.status}</p>{row.source_url&&<a href={row.source_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex text-xs font-semibold text-teal-700 underline underline-offset-4 dark:text-teal-300">Open source document</a>}</div><div className="flex gap-2">{row.status==="submitted"&&<><Button size="sm" onClick={()=>review(row,"verified")}><CheckCircle2 className="mr-1 h-4 w-4"/>Verify & publish</Button><Button size="sm" variant="outline" onClick={()=>review(row,"rejected")}><XCircle className="mr-1 h-4 w-4"/>Reject</Button></>}</div></div>):<div className="p-8 text-center text-sm text-muted-foreground"><FileCheck2 className="mx-auto mb-3 h-6 w-6"/>No evidence awaiting review.</div>}</div>}</div>; }
