import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { FileCheck2, Plus } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route = createFileRoute("/_authenticated/seller/evidence")({ component: SellerEvidence });
const TYPES = ["inspection_report", "ownership_document", "service_record", "mileage_record", "recall_notice", "history_report", "other"];

function SellerEvidence() {
  const [cars, setCars] = useState<any[]>([]); const [rows, setRows] = useState<any[]>([]);
  const [carId, setCarId] = useState(""); const [type, setType] = useState("inspection_report"); const [title, setTitle] = useState(""); const [url, setUrl] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const { data: userData } = await supabase.auth.getUser(); if (!userData.user) return; const { data: seller } = await supabase.from("sellers").select("id").eq("profile_id", userData.user.id).maybeSingle(); if (!seller) return; const { data: carRows } = await supabase.from("cars").select("id,title,year").eq("seller_id", seller.id).order("created_at", { ascending: false }); setCars(carRows ?? []); const { data: evidence } = await supabase.from("vehicle_evidence").select("id,title,evidence_type,status,is_public,created_at,cars(title)").eq("submitted_by", userData.user.id).order("created_at", { ascending: false }); setRows(evidence ?? []); };
  useEffect(() => { void load(); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!carId || !title.trim()) return toast.error("Choose a vehicle and add a document title."); setSaving(true); const { data: userData } = await supabase.auth.getUser(); const { error } = await supabase.from("vehicle_evidence").insert({ car_id: carId, submitted_by: userData.user!.id, evidence_type: type, title: title.trim(), source_url: url.trim() || null }); setSaving(false); if (error) return toast.error(error.message); toast.success("Evidence submitted for review"); setTitle(""); setUrl(""); void load(); };
  return <div className="space-y-6"><header className="rounded-3xl border border-teal-100 bg-teal-50/60 p-6 dark:border-teal-500/20 dark:bg-teal-500/10"><p className="text-xs font-bold uppercase tracking-[.15em] text-teal-700 dark:text-teal-300">Vehicle evidence</p><h1 className="mt-2 text-3xl font-extrabold">Submit facts, not promises.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Attach a document link for admin review. It is private until approved and explicitly made public.</p></header><form onSubmit={submit} className="rounded-3xl border bg-card p-6 sm:p-8"><h2 className="flex items-center gap-2 font-bold"><Plus className="h-4 w-4 text-teal-600"/>Submit evidence</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Vehicle</Label><Select value={carId} onValueChange={setCarId}><SelectTrigger><SelectValue placeholder="Choose a vehicle"/></SelectTrigger><SelectContent>{cars.map((car) => <SelectItem value={car.id} key={car.id}>{car.year} {car.title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Evidence type</Label><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TYPES.map((item) => <SelectItem key={item} value={item}>{item.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Document title</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Independent inspection – 12 Sep 2026"/></div><div className="space-y-2"><Label>Secure document URL (optional)</Label><Input type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://…"/></div></div><Button className="mt-6 rounded-xl" disabled={saving}>{saving ? "Submitting…" : "Submit for review"}</Button></form><section><h2 className="text-lg font-bold">Your submitted evidence</h2><div className="mt-4 overflow-hidden rounded-2xl border bg-card">{rows.length ? rows.map((row) => <div className="flex items-center justify-between gap-3 border-b p-4 last:border-0" key={row.id}><div><p className="font-medium">{row.title}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{(Array.isArray(row.cars) ? row.cars[0] : row.cars)?.title || "Vehicle"} · {row.evidence_type.replaceAll("_", " ")}</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs capitalize">{row.status}</span></div>) : <p className="p-6 text-sm text-muted-foreground">No evidence submitted yet.</p>}</div></section></div>;
}
