/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as HowPaymentsWorkRouteImport } from './routes/how-payments-work'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ImportTrackerRouteImport } from './routes/import-tracker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as YardsRouteImport } from './routes/yards'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGarageRouteImport } from './routes/_authenticated/garage'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsIdRouteImport } from './routes/cars.$id'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as YardsIndexRouteImport } from './routes/yards.index'
import { Route as YardsSlugRouteImport } from './routes/yards.$slug'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountFavoritesRouteImport } from './routes/_authenticated/account.favorites'
import { Route as AuthenticatedAccountImportRequestsRouteImport } from './routes/_authenticated/account.import-requests'
import { Route as AuthenticatedAccountInquiriesRouteImport } from './routes/_authenticated/account.inquiries'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account.notifications'
import { Route as AuthenticatedAccountPurchasesRouteImport } from './routes/_authenticated/account.purchases'
import { Route as AuthenticatedAccountVerifyRouteImport } from './routes/_authenticated/account.verify'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin.broadcast'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminImportRequestsRouteImport } from './routes/_authenticated/admin.import-requests'
import { Route as AuthenticatedAdminInspectionsRouteImport } from './routes/_authenticated/admin.inspections'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminMakesRouteImport } from './routes/_authenticated/admin.makes'
import { Route as AuthenticatedAdminSellersRouteImport } from './routes/_authenticated/admin.sellers'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin.verification'
import { Route as AuthenticatedAdminYardsRouteImport } from './routes/_authenticated/admin.yards'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as AuthenticatedSellerDocumentsRouteImport } from './routes/_authenticated/seller.documents'
import { Route as AuthenticatedSellerImportRequestsRouteImport } from './routes/_authenticated/seller.import-requests'
import { Route as AuthenticatedSellerInquiriesRouteImport } from './routes/_authenticated/seller.inquiries'
import { Route as AuthenticatedSellerInspectionsRouteImport } from './routes/_authenticated/seller.inspections'
import { Route as AuthenticatedSellerTransactionsRouteImport } from './routes/_authenticated/seller.transactions'
import { Route as AuthenticatedSellerVerifyRouteImport } from './routes/_authenticated/seller.verify'
import { Route as AuthenticatedSellerYardRouteImport } from './routes/_authenticated/seller.yard'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions.$id'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedAdminInspectionsIndexRouteImport } from './routes/_authenticated/admin.inspections.index'
import { Route as AuthenticatedAdminInspectionsIdRouteImport } from './routes/_authenticated/admin.inspections.$id'
import { Route as AuthenticatedSellerListingsNewRouteImport } from './routes/_authenticated/seller.listings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const HowPaymentsWorkRoute = HowPaymentsWorkRouteImport.update({
  id: '/how-payments-work',
  path: '/how-payments-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportTrackerRoute = ImportTrackerRouteImport.update({
  id: '/import-tracker',
  path: '/import-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const YardsRoute = YardsRouteImport.update({
  id: '/yards',
  path: '/yards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarageRoute = AuthenticatedGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarsRoute,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsRoute,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartsRoute,
} as any)
const YardsIndexRoute = YardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YardsRoute,
} as any)
const YardsSlugRoute = YardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => YardsRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountFavoritesRoute =
  AuthenticatedAccountFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountImportRequestsRoute =
  AuthenticatedAccountImportRequestsRouteImport.update({
    id: '/import-requests',
    path: '/import-requests',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountInquiriesRoute =
  AuthenticatedAccountInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountPurchasesRoute =
  AuthenticatedAccountPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountVerifyRoute =
  AuthenticatedAccountVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRequestsRoute =
  AuthenticatedAdminImportRequestsRouteImport.update({
    id: '/import-requests',
    path: '/import-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInspectionsRoute =
  AuthenticatedAdminInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMakesRoute = AuthenticatedAdminMakesRouteImport.update({
  id: '/makes',
  path: '/makes',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSellersRoute =
  AuthenticatedAdminSellersRouteImport.update({
    id: '/sellers',
    path: '/sellers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminYardsRoute = AuthenticatedAdminYardsRouteImport.update({
  id: '/yards',
  path: '/yards',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerDocumentsRoute =
  AuthenticatedSellerDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerImportRequestsRoute =
  AuthenticatedSellerImportRequestsRouteImport.update({
    id: '/import-requests',
    path: '/import-requests',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerInquiriesRoute =
  AuthenticatedSellerInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerInspectionsRoute =
  AuthenticatedSellerInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerTransactionsRoute =
  AuthenticatedSellerTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerVerifyRoute =
  AuthenticatedSellerVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerYardRoute = AuthenticatedSellerYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/transactions/$id',
    path: '/transactions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminInspectionsIndexRoute =
  AuthenticatedAdminInspectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminInspectionsRoute,
  } as any)
const AuthenticatedAdminInspectionsIdRoute =
  AuthenticatedAdminInspectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInspectionsRoute,
  } as any)
const AuthenticatedSellerListingsNewRoute =
  AuthenticatedSellerListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/disputes': typeof DisputesRoute
  '/how-payments-work': typeof HowPaymentsWorkRoute
  '/import': typeof ImportRoute
  '/import-tracker': typeof ImportTrackerRoute
  '/login': typeof LoginRoute
  '/parts': typeof PartsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/yards': typeof YardsRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cars/$id': typeof CarsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/yards/$slug': typeof YardsSlugRoute
  '/cars/': typeof CarsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/yards/': typeof YardsIndexRoute
  '/account/favorites': typeof AuthenticatedAccountFavoritesRoute
  '/account/import-requests': typeof AuthenticatedAccountImportRequestsRoute
  '/account/inquiries': typeof AuthenticatedAccountInquiriesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/purchases': typeof AuthenticatedAccountPurchasesRoute
  '/account/verify': typeof AuthenticatedAccountVerifyRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/import-requests': typeof AuthenticatedAdminImportRequestsRoute
  '/admin/inspections': typeof AuthenticatedAdminInspectionsRouteWithChildren
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/makes': typeof AuthenticatedAdminMakesRoute
  '/admin/sellers': typeof AuthenticatedAdminSellersRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/admin/yards': typeof AuthenticatedAdminYardsRoute
  '/seller/documents': typeof AuthenticatedSellerDocumentsRoute
  '/seller/import-requests': typeof AuthenticatedSellerImportRequestsRoute
  '/seller/inquiries': typeof AuthenticatedSellerInquiriesRoute
  '/seller/inspections': typeof AuthenticatedSellerInspectionsRoute
  '/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/seller/verify': typeof AuthenticatedSellerVerifyRoute
  '/seller/yard': typeof AuthenticatedSellerYardRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/admin/inspections/$id': typeof AuthenticatedAdminInspectionsIdRoute
  '/seller/listings/new': typeof AuthenticatedSellerListingsNewRoute
  '/admin/inspections/': typeof AuthenticatedAdminInspectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/disputes': typeof DisputesRoute
  '/how-payments-work': typeof HowPaymentsWorkRoute
  '/import': typeof ImportRoute
  '/import-tracker': typeof ImportTrackerRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/admin/login': typeof AdminLoginRoute
  '/cars/$id': typeof CarsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/yards/$slug': typeof YardsSlugRoute
  '/cars': typeof CarsIndexRoute
  '/parts': typeof PartsIndexRoute
  '/yards': typeof YardsIndexRoute
  '/account/favorites': typeof AuthenticatedAccountFavoritesRoute
  '/account/import-requests': typeof AuthenticatedAccountImportRequestsRoute
  '/account/inquiries': typeof AuthenticatedAccountInquiriesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/purchases': typeof AuthenticatedAccountPurchasesRoute
  '/account/verify': typeof AuthenticatedAccountVerifyRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/import-requests': typeof AuthenticatedAdminImportRequestsRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/makes': typeof AuthenticatedAdminMakesRoute
  '/admin/sellers': typeof AuthenticatedAdminSellersRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/admin/yards': typeof AuthenticatedAdminYardsRoute
  '/seller/documents': typeof AuthenticatedSellerDocumentsRoute
  '/seller/import-requests': typeof AuthenticatedSellerImportRequestsRoute
  '/seller/inquiries': typeof AuthenticatedSellerInquiriesRoute
  '/seller/inspections': typeof AuthenticatedSellerInspectionsRoute
  '/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/seller/verify': typeof AuthenticatedSellerVerifyRoute
  '/seller/yard': typeof AuthenticatedSellerYardRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/admin/inspections/$id': typeof AuthenticatedAdminInspectionsIdRoute
  '/seller/listings/new': typeof AuthenticatedSellerListingsNewRoute
  '/admin/inspections': typeof AuthenticatedAdminInspectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/compare': typeof CompareRoute
  '/disputes': typeof DisputesRoute
  '/how-payments-work': typeof HowPaymentsWorkRoute
  '/import': typeof ImportRoute
  '/import-tracker': typeof ImportTrackerRoute
  '/login': typeof LoginRoute
  '/parts': typeof PartsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/yards': typeof YardsRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/garage': typeof AuthenticatedGarageRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/cars/$id': typeof CarsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/yards/$slug': typeof YardsSlugRoute
  '/cars/': typeof CarsIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/yards/': typeof YardsIndexRoute
  '/_authenticated/account/favorites': typeof AuthenticatedAccountFavoritesRoute
  '/_authenticated/account/import-requests': typeof AuthenticatedAccountImportRequestsRoute
  '/_authenticated/account/inquiries': typeof AuthenticatedAccountInquiriesRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/purchases': typeof AuthenticatedAccountPurchasesRoute
  '/_authenticated/account/verify': typeof AuthenticatedAccountVerifyRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/import-requests': typeof AuthenticatedAdminImportRequestsRoute
  '/_authenticated/admin/inspections': typeof AuthenticatedAdminInspectionsRouteWithChildren
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/makes': typeof AuthenticatedAdminMakesRoute
  '/_authenticated/admin/sellers': typeof AuthenticatedAdminSellersRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/admin/yards': typeof AuthenticatedAdminYardsRoute
  '/_authenticated/seller/documents': typeof AuthenticatedSellerDocumentsRoute
  '/_authenticated/seller/import-requests': typeof AuthenticatedSellerImportRequestsRoute
  '/_authenticated/seller/inquiries': typeof AuthenticatedSellerInquiriesRoute
  '/_authenticated/seller/inspections': typeof AuthenticatedSellerInspectionsRoute
  '/_authenticated/seller/transactions': typeof AuthenticatedSellerTransactionsRoute
  '/_authenticated/seller/verify': typeof AuthenticatedSellerVerifyRoute
  '/_authenticated/seller/yard': typeof AuthenticatedSellerYardRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/admin/inspections/$id': typeof AuthenticatedAdminInspectionsIdRoute
  '/_authenticated/seller/listings/new': typeof AuthenticatedSellerListingsNewRoute
  '/_authenticated/admin/inspections/': typeof AuthenticatedAdminInspectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars'
    | '/compare'
    | '/disputes'
    | '/how-payments-work'
    | '/import'
    | '/import-tracker'
    | '/login'
    | '/parts'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/trust'
    | '/yards'
    | '/account'
    | '/admin'
    | '/complete-profile'
    | '/dashboard'
    | '/garage'
    | '/seller'
    | '/admin/login'
    | '/cars/$id'
    | '/parts/$id'
    | '/yards/$slug'
    | '/cars/'
    | '/parts/'
    | '/yards/'
    | '/account/favorites'
    | '/account/import-requests'
    | '/account/inquiries'
    | '/account/notifications'
    | '/account/purchases'
    | '/account/verify'
    | '/admin/broadcast'
    | '/admin/documents'
    | '/admin/import-requests'
    | '/admin/inspections'
    | '/admin/listings'
    | '/admin/makes'
    | '/admin/sellers'
    | '/admin/transactions'
    | '/admin/verification'
    | '/admin/yards'
    | '/seller/documents'
    | '/seller/import-requests'
    | '/seller/inquiries'
    | '/seller/inspections'
    | '/seller/transactions'
    | '/seller/verify'
    | '/seller/yard'
    | '/transactions/$id'
    | '/api/public/stripe-webhook'
    | '/account/'
    | '/admin/'
    | '/seller/'
    | '/admin/inspections/$id'
    | '/seller/listings/new'
    | '/admin/inspections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/disputes'
    | '/how-payments-work'
    | '/import'
    | '/import-tracker'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/trust'
    | '/complete-profile'
    | '/dashboard'
    | '/garage'
    | '/admin/login'
    | '/cars/$id'
    | '/parts/$id'
    | '/yards/$slug'
    | '/cars'
    | '/parts'
    | '/yards'
    | '/account/favorites'
    | '/account/import-requests'
    | '/account/inquiries'
    | '/account/notifications'
    | '/account/purchases'
    | '/account/verify'
    | '/admin/broadcast'
    | '/admin/documents'
    | '/admin/import-requests'
    | '/admin/listings'
    | '/admin/makes'
    | '/admin/sellers'
    | '/admin/transactions'
    | '/admin/verification'
    | '/admin/yards'
    | '/seller/documents'
    | '/seller/import-requests'
    | '/seller/inquiries'
    | '/seller/inspections'
    | '/seller/transactions'
    | '/seller/verify'
    | '/seller/yard'
    | '/transactions/$id'
    | '/api/public/stripe-webhook'
    | '/account'
    | '/admin'
    | '/seller'
    | '/admin/inspections/$id'
    | '/seller/listings/new'
    | '/admin/inspections'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cars'
    | '/compare'
    | '/disputes'
    | '/how-payments-work'
    | '/import'
    | '/import-tracker'
    | '/login'
    | '/parts'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/support'
    | '/terms'
    | '/trust'
    | '/yards'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/complete-profile'
    | '/_authenticated/dashboard'
    | '/_authenticated/garage'
    | '/_authenticated/seller'
    | '/admin/login'
    | '/cars/$id'
    | '/parts/$id'
    | '/yards/$slug'
    | '/cars/'
    | '/parts/'
    | '/yards/'
    | '/_authenticated/account/favorites'
    | '/_authenticated/account/import-requests'
    | '/_authenticated/account/inquiries'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/purchases'
    | '/_authenticated/account/verify'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/import-requests'
    | '/_authenticated/admin/inspections'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/makes'
    | '/_authenticated/admin/sellers'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/verification'
    | '/_authenticated/admin/yards'
    | '/_authenticated/seller/documents'
    | '/_authenticated/seller/import-requests'
    | '/_authenticated/seller/inquiries'
    | '/_authenticated/seller/inspections'
    | '/_authenticated/seller/transactions'
    | '/_authenticated/seller/verify'
    | '/_authenticated/seller/yard'
    | '/_authenticated/transactions/$id'
    | '/api/public/stripe-webhook'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/seller/'
    | '/_authenticated/admin/inspections/$id'
    | '/_authenticated/seller/listings/new'
    | '/_authenticated/admin/inspections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CarsRoute: typeof CarsRouteWithChildren
  CompareRoute: typeof CompareRoute
  DisputesRoute: typeof DisputesRoute
  HowPaymentsWorkRoute: typeof HowPaymentsWorkRoute
  ImportRoute: typeof ImportRoute
  ImportTrackerRoute: typeof ImportTrackerRoute
  LoginRoute: typeof LoginRoute
  PartsRoute: typeof PartsRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  YardsRoute: typeof YardsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-payments-work': {
      id: '/how-payments-work'
      path: '/how-payments-work'
      fullPath: '/how-payments-work'
      preLoaderRoute: typeof HowPaymentsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-tracker': {
      id: '/import-tracker'
      path: '/import-tracker'
      fullPath: '/import-tracker'
      preLoaderRoute: typeof ImportTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yards': {
      id: '/yards'
      path: '/yards'
      fullPath: '/yards'
      preLoaderRoute: typeof YardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garage': {
      id: '/_authenticated/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AuthenticatedGarageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof CarsRoute
    }
    '/parts/': {
      id: '/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof PartsRoute
    }
    '/yards/': {
      id: '/yards/'
      path: '/'
      fullPath: '/yards/'
      preLoaderRoute: typeof YardsIndexRouteImport
      parentRoute: typeof YardsRoute
    }
    '/yards/$slug': {
      id: '/yards/$slug'
      path: '/$slug'
      fullPath: '/yards/$slug'
      preLoaderRoute: typeof YardsSlugRouteImport
      parentRoute: typeof YardsRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/favorites': {
      id: '/_authenticated/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AuthenticatedAccountFavoritesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/import-requests': {
      id: '/_authenticated/account/import-requests'
      path: '/import-requests'
      fullPath: '/account/import-requests'
      preLoaderRoute: typeof AuthenticatedAccountImportRequestsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/inquiries': {
      id: '/_authenticated/account/inquiries'
      path: '/inquiries'
      fullPath: '/account/inquiries'
      preLoaderRoute: typeof AuthenticatedAccountInquiriesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/purchases': {
      id: '/_authenticated/account/purchases'
      path: '/purchases'
      fullPath: '/account/purchases'
      preLoaderRoute: typeof AuthenticatedAccountPurchasesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/verify': {
      id: '/_authenticated/account/verify'
      path: '/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AuthenticatedAccountVerifyRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import-requests': {
      id: '/_authenticated/admin/import-requests'
      path: '/import-requests'
      fullPath: '/admin/import-requests'
      preLoaderRoute: typeof AuthenticatedAdminImportRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inspections': {
      id: '/_authenticated/admin/inspections'
      path: '/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AuthenticatedAdminInspectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/makes': {
      id: '/_authenticated/admin/makes'
      path: '/makes'
      fullPath: '/admin/makes'
      preLoaderRoute: typeof AuthenticatedAdminMakesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sellers': {
      id: '/_authenticated/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AuthenticatedAdminSellersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/yards': {
      id: '/_authenticated/admin/yards'
      path: '/yards'
      fullPath: '/admin/yards'
      preLoaderRoute: typeof AuthenticatedAdminYardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/documents': {
      id: '/_authenticated/seller/documents'
      path: '/documents'
      fullPath: '/seller/documents'
      preLoaderRoute: typeof AuthenticatedSellerDocumentsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/import-requests': {
      id: '/_authenticated/seller/import-requests'
      path: '/import-requests'
      fullPath: '/seller/import-requests'
      preLoaderRoute: typeof AuthenticatedSellerImportRequestsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/inquiries': {
      id: '/_authenticated/seller/inquiries'
      path: '/inquiries'
      fullPath: '/seller/inquiries'
      preLoaderRoute: typeof AuthenticatedSellerInquiriesRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/inspections': {
      id: '/_authenticated/seller/inspections'
      path: '/inspections'
      fullPath: '/seller/inspections'
      preLoaderRoute: typeof AuthenticatedSellerInspectionsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/transactions': {
      id: '/_authenticated/seller/transactions'
      path: '/transactions'
      fullPath: '/seller/transactions'
      preLoaderRoute: typeof AuthenticatedSellerTransactionsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/verify': {
      id: '/_authenticated/seller/verify'
      path: '/verify'
      fullPath: '/seller/verify'
      preLoaderRoute: typeof AuthenticatedSellerVerifyRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/yard': {
      id: '/_authenticated/seller/yard'
      path: '/yard'
      fullPath: '/seller/yard'
      preLoaderRoute: typeof AuthenticatedSellerYardRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/inspections/': {
      id: '/_authenticated/admin/inspections/'
      path: '/'
      fullPath: '/admin/inspections/'
      preLoaderRoute: typeof AuthenticatedAdminInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminInspectionsRoute
    }
    '/_authenticated/admin/inspections/$id': {
      id: '/_authenticated/admin/inspections/$id'
      path: '/$id'
      fullPath: '/admin/inspections/$id'
      preLoaderRoute: typeof AuthenticatedAdminInspectionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminInspectionsRoute
    }
    '/_authenticated/seller/listings/new': {
      id: '/_authenticated/seller/listings/new'
      path: '/listings/new'
      fullPath: '/seller/listings/new'
      preLoaderRoute: typeof AuthenticatedSellerListingsNewRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountFavoritesRoute: typeof AuthenticatedAccountFavoritesRoute
  AuthenticatedAccountImportRequestsRoute: typeof AuthenticatedAccountImportRequestsRoute
  AuthenticatedAccountInquiriesRoute: typeof AuthenticatedAccountInquiriesRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountPurchasesRoute: typeof AuthenticatedAccountPurchasesRoute
  AuthenticatedAccountVerifyRoute: typeof AuthenticatedAccountVerifyRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountFavoritesRoute: AuthenticatedAccountFavoritesRoute,
  AuthenticatedAccountImportRequestsRoute:
    AuthenticatedAccountImportRequestsRoute,
  AuthenticatedAccountInquiriesRoute: AuthenticatedAccountInquiriesRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountPurchasesRoute: AuthenticatedAccountPurchasesRoute,
  AuthenticatedAccountVerifyRoute: AuthenticatedAccountVerifyRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminInspectionsRouteChildren {
  AuthenticatedAdminInspectionsIdRoute: typeof AuthenticatedAdminInspectionsIdRoute
  AuthenticatedAdminInspectionsIndexRoute: typeof AuthenticatedAdminInspectionsIndexRoute
}

const AuthenticatedAdminInspectionsRouteChildren: AuthenticatedAdminInspectionsRouteChildren =
  {
    AuthenticatedAdminInspectionsIdRoute: AuthenticatedAdminInspectionsIdRoute,
    AuthenticatedAdminInspectionsIndexRoute:
      AuthenticatedAdminInspectionsIndexRoute,
  }

const AuthenticatedAdminInspectionsRouteWithChildren =
  AuthenticatedAdminInspectionsRoute._addFileChildren(
    AuthenticatedAdminInspectionsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminImportRequestsRoute: typeof AuthenticatedAdminImportRequestsRoute
  AuthenticatedAdminInspectionsRoute: typeof AuthenticatedAdminInspectionsRouteWithChildren
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminMakesRoute: typeof AuthenticatedAdminMakesRoute
  AuthenticatedAdminSellersRoute: typeof AuthenticatedAdminSellersRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
  AuthenticatedAdminYardsRoute: typeof AuthenticatedAdminYardsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminImportRequestsRoute: AuthenticatedAdminImportRequestsRoute,
  AuthenticatedAdminInspectionsRoute:
    AuthenticatedAdminInspectionsRouteWithChildren,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminMakesRoute: AuthenticatedAdminMakesRoute,
  AuthenticatedAdminSellersRoute: AuthenticatedAdminSellersRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
  AuthenticatedAdminYardsRoute: AuthenticatedAdminYardsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerDocumentsRoute: typeof AuthenticatedSellerDocumentsRoute
  AuthenticatedSellerImportRequestsRoute: typeof AuthenticatedSellerImportRequestsRoute
  AuthenticatedSellerInquiriesRoute: typeof AuthenticatedSellerInquiriesRoute
  AuthenticatedSellerInspectionsRoute: typeof AuthenticatedSellerInspectionsRoute
  AuthenticatedSellerTransactionsRoute: typeof AuthenticatedSellerTransactionsRoute
  AuthenticatedSellerVerifyRoute: typeof AuthenticatedSellerVerifyRoute
  AuthenticatedSellerYardRoute: typeof AuthenticatedSellerYardRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
  AuthenticatedSellerListingsNewRoute: typeof AuthenticatedSellerListingsNewRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerDocumentsRoute: AuthenticatedSellerDocumentsRoute,
  AuthenticatedSellerImportRequestsRoute:
    AuthenticatedSellerImportRequestsRoute,
  AuthenticatedSellerInquiriesRoute: AuthenticatedSellerInquiriesRoute,
  AuthenticatedSellerInspectionsRoute: AuthenticatedSellerInspectionsRoute,
  AuthenticatedSellerTransactionsRoute: AuthenticatedSellerTransactionsRoute,
  AuthenticatedSellerVerifyRoute: AuthenticatedSellerVerifyRoute,
  AuthenticatedSellerYardRoute: AuthenticatedSellerYardRoute,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
  AuthenticatedSellerListingsNewRoute: AuthenticatedSellerListingsNewRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGarageRoute: typeof AuthenticatedGarageRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGarageRoute: AuthenticatedGarageRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CarsRouteChildren {
  CarsIdRoute: typeof CarsIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsIdRoute: CarsIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface PartsRouteChildren {
  PartsIdRoute: typeof PartsIdRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsIdRoute: PartsIdRoute,
  PartsIndexRoute: PartsIndexRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

interface YardsRouteChildren {
  YardsSlugRoute: typeof YardsSlugRoute
  YardsIndexRoute: typeof YardsIndexRoute
}

const YardsRouteChildren: YardsRouteChildren = {
  YardsSlugRoute: YardsSlugRoute,
  YardsIndexRoute: YardsIndexRoute,
}

const YardsRouteWithChildren = YardsRoute._addFileChildren(YardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CarsRoute: CarsRouteWithChildren,
  CompareRoute: CompareRoute,
  DisputesRoute: DisputesRoute,
  HowPaymentsWorkRoute: HowPaymentsWorkRoute,
  ImportRoute: ImportRoute,
  ImportTrackerRoute: ImportTrackerRoute,
  LoginRoute: LoginRoute,
  PartsRoute: PartsRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  YardsRoute: YardsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
